name: biochef_app
description: "BioChef AI - Il tuo chef intelligente di famiglia."
publish_to: 'none'

# Aggiornato a 0.1.7 per permettere l'update sul telefono
version: 0.1.9+20

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0

  intl: ^0.20.2
  package_info_plus: ^10.0.0
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# Configurazione Icona App (Root level)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icona_app.png"
  adaptive_icon_background: "#1B4332"
  adaptive_icon_foreground: "assets/icona_app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/          # <--- Registra TUTTA la cartella così vede ogni foto che aggiungi
    - assets/icona_app.png